sudo: required

dist: trusty

addons:
   chrome: stable

language: php

php:
  - 7.2

before_install:
  - sudo apt-get install -y libsqlite3-dev
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
   - cp .env.dusk.testing .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - travis_retry composer self-update
  - php artisan key:generate
  - touch database/database.sqlite
  - php artisan migrate --env=testing --force
  - php artisan db:seed
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - ./vendor/laravel/dusk/bin/chromedriver-linux
  - php artisan serve
  - vendor/bin/phpunit
  - php artisan dusk
